### ISSUE TITLE
Repeated use causes exponential slowdown in VS2015

### ISSUE THREAD

**Issue by terriblememory** [abmes/SyntaxHighlighter#2]
In VS2015 I was finding that after five or six Edit|Refactor|Rename operations in C# projects the rename became terribly slow, and it just got worse after that - by the 10th-20th rename it was taking minutes. VS performance was otherwise good. Eventually I found that turning this extension off fixed the problem.

[See this stackoverflow thread for a little more information.](http://stackoverflow.com/questions/32214291/visual-studio-2015-c-sharp-rename-horribly-slow)

**Comment by metatem** [comment]
Thanks for your feedback. I will look into that problem as soon as I can.

**Comment by metatem** [comment]
Closing the issue because we are dropping support for the Syntax Highlighter and will develop only the new version - [Semantic Highlighter](https://github.com/abmes/SemanticHighlighter)
