### ISSUE TITLE
Will there be a version for VS2017?

### ISSUE THREAD

**Issue by lhummel64** [abmes/SyntaxHighlighter#4]

**Comment by metatem** [comment]
Yes. We will upgrade to VS2017. I hope I can find the time to do it in the upcoming weeks.

**Comment by metatem** [comment]
It looks like the upgrade to VS 2017 will not be as straight forward as I hoped. You can achieve similar coloring in VS 2017 by using the "Punctuation" element which combines the delimiters and the braces, brackets, etc. and for the namespace you can use the [Semantic Syntax Colorizer](https://github.com/hicknhack-software/semantic-colorizer) which works with VS 2017 and uses the Roslyn API so I expect it to be more accurate.

**Comment by metatem** [comment]
We have created a new version for VS 2017 as an entirely new project - [Semantic Highlighter](https://github.com/abmes/SemanticHighlighter). You can try it out. It is available in the visual studio gallery. It uses the Roslyn API so it is much more reliable and robust. We can extend it much more easily. 

We will leave this repository and extension (the Syntax Highlighter) here but all new features probably will not be implemented for it. So please use the new [Semantic Highlighter](https://github.com/abmes/SemanticHighlighter) and give us your feedback and/or suggestions for new features and improvements.
